---
  - name: add rpm repo
    yum: name=https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
      
  
  - name: 'install zabbix agent'
    yum: name=zabbix-agent
  
  
  - name: 'config firewalld'
    firewalld: 
      port: 10050/tcp
      permanent: true
      state: enabled
      immediate: yes

  - name: reload firewall
    service:
      name: firewalld
      state: restarted
 
  - name: 'replace serverActive in config file with appropriate'
    template:
            src: zabbix_agentd.conf 
            dest: /etc/zabbix/zabbix_agentd.conf
 
  
  - name: 'start and enable zabbix agent'
    service:
      name: zabbix-agent
      state: started
      enabled: yes
